## Default values.yaml for Telegraf
## This is a YAML-formatted file.
## ref: https://hub.docker.com/r/library/telegraf/tags/

replicaCount: 1
image:
  repo: "docker.io/library/telegraf"
  tag: "1.32.1-alpine"
  pullPolicy: IfNotPresent
podAnnotations: {}
podLabels: {}
imagePullSecrets: []
## Configure args passed to Telegraf containers
args: []
# The name of a secret in the same kubernetes namespace which contains values to
# be added to the environment (must be manually created)
# This can be useful for auth tokens, etc.

# envFromSecret: "telegraf-tokens"
env:
  - name: HOSTNAME
    value: "telegraf-polling-service"
# An older "volumeMounts" key was previously added which will likely
# NOT WORK as you expect. Please use this newer configuration.

volumes:
  - name: telegraf-ca
    secret:
      secretName: telegraf-ca

mountPoints:
  - name: telegraf-ca
    mountPath: /etc/telegraf/ca
    readOnly: true      

## Configure resource requests and limits
## ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources: {}
requests:
  memory: 64Mi
  cpu: 50m
limits:
  memory: 128Mi
  cpu: 100m

## Node labels for pod assignment
## ref: https://kubernetes.io/docs/user-guide/node-selection/
nodeSelector: {}
## Affinity for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity
##
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - worker04

## Tolerations for pod assignment
## Ref: https://kubernetes.io/docs/concepts/configuration/taint-and-toleration/
##
tolerations: []
# - key: "key"
#   operator: "Equal|Exists"
#   value: "value"
#   effect: "NoSchedule|PreferNoSchedule|NoExecute(1.6 only)"

## Configure the updateStrategy used to replace Telegraf Pods
## See https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/deployment-v1/
updateStrategy: {}
#  type: RollingUpdate|Recreate
#  rollingUpdate:
#    maxUnavailable: 1
#    maxSurge: 1

service:
  enabled: false
rbac:
  # Specifies whether RBAC resources should be created
  create: true
  # Create only for the release namespace or cluster wide (Role vs ClusterRole)
  clusterWide: false
  # Rules for the created rule
  rules: []
# When using the prometheus input to scrape all pods you need extra rules set to the ClusterRole to be
# able to scan the pods for scraping labels. The following rules have been taken from:
# https://github.com/helm/charts/blob/master/stable/prometheus/templates/server-clusterrole.yaml#L8-L46
#    - apiGroups:
#        - ""
#      resources:
#        - nodes
#        - nodes/proxy
#        - nodes/metrics
#        - services
#        - endpoints
#        - pods
#        - ingresses
#        - configmaps
#      verbs:
#        - get
#        - list
#        - watch
#    - apiGroups:
#        - "extensions"
#      resources:
#        - ingresses/status
#        - ingresses
#      verbs:
#        - get
#        - list
#        - watch
#    - nonResourceURLs:
#        - "/metrics"
#      verbs:
#        - get

serviceAccount:
  # Specifies whether a ServiceAccount should be created
  create: true
  # The name of the ServiceAccount to use.
  # If not set and create is true, a name is generated using the fullname template
  name: telegraf
  # Annotations for the ServiceAccount
  annotations: {}
## Exposed telegraf configuration
## For full list of possible values see `/docs/all-config-values.yaml` and `/docs/all-config-values.toml`
## ref: https://docs.influxdata.com/telegraf/v1.1/administration/configuration/
config:
  agent:
    interval: "15s"
    round_interval: true
    metric_batch_size: 10000
    metric_buffer_limit: 200000
    collection_jitter: "0s"
    flush_interval: "15s"
    flush_jitter: "0s"
    precision: ""
    debug: true
    quiet: false
    logfile: ""
    hostname: "$HOSTNAME"
    omit_hostname: false
  processors:
    - enum:
        mapping:
          field: "status"
          dest: "status_code"
          value_mappings:
            healthy: 1
            problem: 2
            critical: 3

    - starlark:
        namepass: ["node_cpu_seconds_total"]
        source: |
          def apply(metric):
              url = metric.tags.get("url", "")
              ip = ""

              # Extraer IP desde URL sin usar re
              parts = url.split("://")
              if len(parts) > 1:
                  ip_port = parts[1].split(":")
                  if len(ip_port) > 0:
                      ip = ip_port[0]

              ip_map = {
                  "192.168.1.220": "master01",
                  "192.168.1.221": "worker01",
                  "192.168.1.222": "worker02",
                  "192.168.1.223": "worker03",
                  "192.168.1.224": "worker04",
                  "192.168.1.225": "worker05"
              }

              metric.tags["nodo"] = ip_map.get(ip, "desconocido")

              if metric.name == "node_cpu_seconds_total" and metric.tags.get("mode") == "idle":
                  v = metric.fields.get("value")
                  if v == None:
                      return metric

                  idle = float(v)

                  if ip in ["192.168.1.220", "192.168.1.221", "192.168.1.222", "192.168.1.223"]:
                      idle_w = 4.5
                      load_w = 10.0
                  elif ip in ["192.168.1.224", "192.168.1.225"]:
                      idle_w = 3.4
                      load_w = 6.4
                  else:
                      idle_w = 3.5
                      load_w = 7.0

                  cpu_usage = 100 - (idle * 100)
                  power = idle_w + (cpu_usage / 100) * (load_w - idle_w)

                  # Redondear manualmente a 2 decimales
                  power_rounded = int(power * 100) / 100.0

                  metric.fields["rpi_power_watts"] = power_rounded

              return metric
  outputs:
    - influxdb_v2:
        urls: ["http://influxdb-influxdb2:80"]
        token: "klsjdaioqwehrqoikdnmxcq"
        organization: "uclm"
        bucket: "doctorado"
        namepass:
        - node_cpu_seconds_total
        - node_disk_reads_completed_total
        - node_disk_writes_completed_total
        - node_disk_read_bytes_total
        - node_disk_written_bytes_total
        - node_filesystem_size_bytes
        - node_filesystem_free_bytes
        - node_filesystem_avail_bytes
        - node_filesystem_files
        - node_network_receive_bytes_total
        - node_network_transmit_bytes_total
        - node_network_receive_packets_total
        - node_network_transmit_packets_total          
  inputs:
    - prometheus:
        tls_ca: "/etc/telegraf/ca/ca.crt"
        insecure_skip_verify: true
        urls:
          - https://192.168.1.220:9100/metrics
          - https://192.168.1.221:9100/metrics
          - https://192.168.1.222:9100/metrics
          - https://192.168.1.223:9100/metrics
          - https://192.168.1.224:9100/metrics
          - https://192.168.1.225:9100/metrics
metrics:
  health:
    enabled: false
    service_address: "http://:8888"
    threshold: 5000.0
  internal:
    enabled: true
    collect_memstats: false
# Lifecycle hooks
# hooks:
#   postStart: ["/bin/sh", "-c", "echo Telegraf started"]
#   preStop: ["/bin/sh", "-c", "sleep 60"]

## Pod disruption budget configuration
##
pdb:
  ## Specifies whether a Pod disruption budget should be created
  ##
  create: false
  minAvailable: 1
  # maxUnavailable: 1

# containerPorts:
# - name: http
#   containerPort: 9273
#   protocol: TCP

