defaultRules:
  create: false

kube-state-metrics:
  enabled: false

alertmanager:
  enabled: false

grafana:
  enabled: false

prometheus:
  enabled: false

prometheusOperator:
  enabled: false

prometheus-node-exporter:
  extraArgs:
    - --collector.disable-defaults
    - --collector.cpu
    - --collector.diskstats
    - --collector.netdev
    - --collector.netstat
    - --collector.filesystem
<<<<<<< Updated upstream
=======
  resources:
>>>>>>> Stashed changes
  resources:
    limits:
      cpu: 100m
      memory: 50Mi
    requests:
      cpu: 50m
      memory: 30Mi
