apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: operator
  name: scheduler
  labels:
    app: scheduler
    component: scheduler
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scheduler
subjects:
- kind: ServiceAccount
  name: scheduler
  namespace: operator
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:kube-scheduler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: scheduler
  namespace: operator
  labels:
    app: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scheduler
  template:
    metadata:
      labels:
        app: scheduler
    spec:
      serviceAccount: scheduler
      containers:
        - name: scheduler
          image: 192.168.1.229:5000/doctorado/influxsdb-scheduler:0.0.0
          imagePullPolicy: Always
          env:
            - name: SCHEDULER_NAME
              value: "random"