# permissions for end users to view influxdbmetricsschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: influxdbmetricsscheduler-viewer-role
rules:
- apiGroups:
  - scheduler.uclm.es
  resources:
  - influxdbmetricsschedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - scheduler.uclm.es
  resources:
  - influxdbmetricsschedulers/status
  verbs:
  - get
