# permissions for end users to edit tsmetricsschedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: tsmetricsscheduler-editor-role
rules:
- apiGroups:
  - scheduler.uclm.es
  resources:
  - tsmetricsschedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - scheduler.uclm.es
  resources:
  - tsmetricsschedulers/status
  verbs:
  - get
