
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: scheduler-operator
  namespace: operator
  labels:
    control-plane: scheduler-operator
data:
  # LOG Config
  LOG_DEV_MODE: "true"
  LOG_ENCODER: "console"
  LOG_LEVEL_OPERATOR: "debug"
  LOG_LEVEL_STRACKTRACE: "error"

  # Namespaces to Watch
  WATCH_NAMESPACES: ""

  # Image Config
  IMG_METRICSCHEDULER: "192.168.1.229:5000/doctorado/scheduler:0.0.0"
