//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1

import (
	corev1 "k8s.io/api/core/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConstraintsSpec) DeepCopyInto(out *ConstraintsSpec) {
	*out = *in
	if in.Affinity != nil {
		in, out := &in.Affinity, &out.Affinity
		*out = new(corev1.Affinity)
		(*in).DeepCopyInto(*out)
	}
	if in.TopologySpreadConstraint != nil {
		in, out := &in.TopologySpreadConstraint, &out.TopologySpreadConstraint
		*out = make([]corev1.TopologySpreadConstraint, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Tolerations != nil {
		in, out := &in.Tolerations, &out.Tolerations
		*out = make([]corev1.Toleration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConstraintsSpec.
func (in *ConstraintsSpec) DeepCopy() *ConstraintsSpec {
	if in == nil {
		return nil
	}
	out := new(ConstraintsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *HealthchecksSpec) DeepCopyInto(out *HealthchecksSpec) {
	*out = *in
	if in.StartupProbe != nil {
		in, out := &in.StartupProbe, &out.StartupProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.ReadinessProbe != nil {
		in, out := &in.ReadinessProbe, &out.ReadinessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
	if in.LivenessProbe != nil {
		in, out := &in.LivenessProbe, &out.LivenessProbe
		*out = new(corev1.Probe)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new HealthchecksSpec.
func (in *HealthchecksSpec) DeepCopy() *HealthchecksSpec {
	if in == nil {
		return nil
	}
	out := new(HealthchecksSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfluxdbMetricsScheduler) DeepCopyInto(out *InfluxdbMetricsScheduler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfluxdbMetricsScheduler.
func (in *InfluxdbMetricsScheduler) DeepCopy() *InfluxdbMetricsScheduler {
	if in == nil {
		return nil
	}
	out := new(InfluxdbMetricsScheduler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfluxdbMetricsScheduler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfluxdbMetricsSchedulerList) DeepCopyInto(out *InfluxdbMetricsSchedulerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InfluxdbMetricsScheduler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfluxdbMetricsSchedulerList.
func (in *InfluxdbMetricsSchedulerList) DeepCopy() *InfluxdbMetricsSchedulerList {
	if in == nil {
		return nil
	}
	out := new(InfluxdbMetricsSchedulerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InfluxdbMetricsSchedulerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfluxdbMetricsSchedulerSpec) DeepCopyInto(out *InfluxdbMetricsSchedulerSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfluxdbMetricsSchedulerSpec.
func (in *InfluxdbMetricsSchedulerSpec) DeepCopy() *InfluxdbMetricsSchedulerSpec {
	if in == nil {
		return nil
	}
	out := new(InfluxdbMetricsSchedulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InfluxdbMetricsSchedulerStatus) DeepCopyInto(out *InfluxdbMetricsSchedulerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InfluxdbMetricsSchedulerStatus.
func (in *InfluxdbMetricsSchedulerStatus) DeepCopy() *InfluxdbMetricsSchedulerStatus {
	if in == nil {
		return nil
	}
	out := new(InfluxdbMetricsSchedulerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MetricSpec) DeepCopyInto(out *MetricSpec) {
	*out = *in
	if in.FilterClause != nil {
		in, out := &in.FilterClause, &out.FilterClause
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecondLevelGroup != nil {
		in, out := &in.SecondLevelGroup, &out.SecondLevelGroup
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.SecondLevelSelect != nil {
		in, out := &in.SecondLevelSelect, &out.SecondLevelSelect
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MetricSpec.
func (in *MetricSpec) DeepCopy() *MetricSpec {
	if in == nil {
		return nil
	}
	out := new(MetricSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TimescaledbSpec) DeepCopyInto(out *TimescaledbSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TimescaledbSpec.
func (in *TimescaledbSpec) DeepCopy() *TimescaledbSpec {
	if in == nil {
		return nil
	}
	out := new(TimescaledbSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TsMetricsScheduler) DeepCopyInto(out *TsMetricsScheduler) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TsMetricsScheduler.
func (in *TsMetricsScheduler) DeepCopy() *TsMetricsScheduler {
	if in == nil {
		return nil
	}
	out := new(TsMetricsScheduler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TsMetricsScheduler) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TsMetricsSchedulerList) DeepCopyInto(out *TsMetricsSchedulerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TsMetricsScheduler, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TsMetricsSchedulerList.
func (in *TsMetricsSchedulerList) DeepCopy() *TsMetricsSchedulerList {
	if in == nil {
		return nil
	}
	out := new(TsMetricsSchedulerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TsMetricsSchedulerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TsMetricsSchedulerSpec) DeepCopyInto(out *TsMetricsSchedulerSpec) {
	*out = *in
	if in.Instances != nil {
		in, out := &in.Instances, &out.Instances
		*out = new(int32)
		**out = **in
	}
	in.Resources.DeepCopyInto(&out.Resources)
	in.Healthchecks.DeepCopyInto(&out.Healthchecks)
	if in.Constraints != nil {
		in, out := &in.Constraints, &out.Constraints
		*out = new(ConstraintsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.Timescaledb != nil {
		in, out := &in.Timescaledb, &out.Timescaledb
		*out = new(TimescaledbSpec)
		**out = **in
	}
	if in.Metric != nil {
		in, out := &in.Metric, &out.Metric
		*out = new(MetricSpec)
		(*in).DeepCopyInto(*out)
	}
	in.UpdateStrategy.DeepCopyInto(&out.UpdateStrategy)
	if in.PriorityClassName != nil {
		in, out := &in.PriorityClassName, &out.PriorityClassName
		*out = new(string)
		**out = **in
	}
	if in.FilterNodes != nil {
		in, out := &in.FilterNodes, &out.FilterNodes
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TsMetricsSchedulerSpec.
func (in *TsMetricsSchedulerSpec) DeepCopy() *TsMetricsSchedulerSpec {
	if in == nil {
		return nil
	}
	out := new(TsMetricsSchedulerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TsMetricsSchedulerStatus) DeepCopyInto(out *TsMetricsSchedulerStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TsMetricsSchedulerStatus.
func (in *TsMetricsSchedulerStatus) DeepCopy() *TsMetricsSchedulerStatus {
	if in == nil {
		return nil
	}
	out := new(TsMetricsSchedulerStatus)
	in.DeepCopyInto(out)
	return out
}
