apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tsmetricsscheduler
subjects:
- kind: ServiceAccount
  name: tsmetricsscheduler
  namespace: scheduling
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: system:kube-scheduler
---
apiVersion: scheduler.uclm.es/v1
kind: TsMetricsScheduler
metadata:
  name: tsmetricsscheduler
  namespace: scheduling
spec:
  image: 192.168.1.229:5000/doctorado/ts-scheduler:0.0.0
  imagePullPolicy: Always
  instances: 1
  resources:
    requests:
      cpu: "100m"
      memory: "256Mi"
    limits:
      cpu: "100m"
      memory: "256Mi"
  healthchecks:
    livenessProbe:
      initialDelaySeconds: 10
      periodSeconds: 10
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 45%
      maxUnavailable: 35%
  filterNodes:
  - tfm-dev
  - tfm-dev-m02
  timescaledb:
    host: timescaledb.monitoring
    port: "5432"
    user: postgres
    password: patroni
    database: tsdb
    authenticationType: MD5
  metric:
    name: "node_network_transmit_bytes_total"
    startDate: "now()- INTERVAL '20 MINUTES'"
    endDate: "now()"
    operation: "Last(value;time)-first(value;time)"
    priorityOrder: "desc"
    filters:
    - "val(device_id)in('eth1')"
    isSecondLevel: false
