---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-batch-uclm-es-v1-metricscheduler
  failurePolicy: Fail
  name: mmetricscheduler.kb.io
  rules:
  - apiGroups:
    - batch.uclm.es
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metricschedulers
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-batch-uclm-es-v1-metricscheduler
  failurePolicy: Fail
  name: vmetricscheduler.kb.io
  rules:
  - apiGroups:
    - batch.uclm.es
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - metricschedulers
  sideEffects: None
